### PR TITLE
Delete node-build.yml

### PR DESCRIPTION
**Pull request by 0atman**
~~This file was for travis - we don't use travis anymore.~~

This file is unused

### CODE REVIEW

**Comment by katstevens** [comment]
Hi @0atman - I think this file is still used in the Concourse PR pipeline?

**Comment by 0atman** [comment]
@katstevens but it's travis, isn't it?

**Comment by 0atman** [comment]
I'm no longer convinced this file is travis :laughing:

**Comment by 0atman** [comment]
OK, it's certainly concourse, we were bamboozled by it being added at the same time as a travis file

**Comment by 0atman** [comment]
But do we use it? :confused:

**Comment by jfharden** [comment]
I think this can be deleted @katstevens the file used in the pr pipeline is node-build-pr.yml https://github.com/alphagov/pay-ci/blob/master/ci/pipelines/pr.yml#L199 and I can't find any reference to node-build.yml in any pipeline in this repo, pay-team-manual, pay-tech-docs or pay-js-commons

**Comment by 0atman** [comment]
:zombie:

**Comment by katstevens** [comment]
@jfharden Ah you're right - I was getting confused with the `node-build-pr.yml`. Now we've got the pipeline verification check we should have more confidence in deleting this, right?

**Review by iqbalgds — APPROVED** [review]

**Comment by jfharden** [comment]
Sadly likely not, if the pipeline refers to a file then it doesn't check to see if that file exists since it's not cloning the other repos it requires. However I'm confident this isn't used and the worst side effect is a step failing in a new build, at which point we can trivially revert this PR since it's so well focussed and just allow the pipeline to be set again automatically.

**Review by jfharden — APPROVED** [review]

**Pull request merged**
