### PR TITLE
PP-13142 Run Bastion E2E test before deploying to test

### PR DESCRIPTION
**Pull request by kbottla**
## WHAT
- Updates bastion pipeline to build candidate image, run E2E test and retag image as release before deploying to test

### Concourse jobs

- Build candidate: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/bastion/jobs/build-and-push-bastion-candidate/builds/3
- E2E test and retag as release - https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/bastion/jobs/bastion-e2e-test-and-retag-image-as-release/builds/1

### CODE REVIEW

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files in Concourse Team pay-deploy**

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/bastion.pkl

<details><summary>Diff of YAML generated from pay-dev/bastion.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/bastion.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/bastion.yml
@@ -1,5 +1,5 @@
 jobs:
-- name: build-and-push-bastion-release
+- name: build-and-push-bastion-candidate
   plan:
   - in_parallel:
     - get: pay-ci
@@ -21,13 +21,6 @@
         USERNAME: ((docker-username))
         PASSWORD: ((docker-access-token))
         EMAIL: ((docker-email))
-    - task: assume-retag-role
-      file: pay-ci/ci/tasks/assume-role.yml
-      params:
-        AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
-        AWS_ROLE_SESSION_NAME: retag-ecr-image-as-release
-      output_mapping:
-        assume-role: assume-retag-role
   - in_parallel:
     - load_var: release-number
       file: tags/release-number
@@ -42,11 +35,6 @@
     - load_var: role
       file: assume-role/assume-role.json
       format: json
-    - load_var: release-image-tag
-      file: tags/tags
-    - load_var: retag-role
-      file: assume-retag-role/assume-role.json
-      format: json
   - task: prepare-codebuild
     file: pay-ci/ci/tasks/prepare-codebuild-multiarch.yml
     params:
@@ -86,32 +74,6 @@
       AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
       AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
       AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
-  - in_parallel:
-    - task: retag-candidate-as-release-in-ecr
-      file: pay-ci/ci/tasks/manifest-retag.yml
-      params:
-        DOCKER_LOGIN_ECR: '1'
-        AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
-        SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
-        NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:release-image-tag))
-        AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
-        AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
-        AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
-    - task: retag-candidate-as-latest-in-ecr
-      file: pay-ci/ci/tasks/manifest-retag.yml
-      params:
-        DOCKER_LOGIN_ECR: '1'
-        AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
-        SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
-        NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:latest
-        AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
-        AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
-        AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
-    - task: retag-candidate-as-release-in-dockerhub
-      file: pay-ci/ci/tasks/manifest-retag.yml
-      params:
-        SOURCE_MANIFEST: governmentdigitalservice/pay-aws-bastion:((.:candidate-image-tag))
-        NEW_MANIFEST: governmentdigitalservice/pay-aws-bastion:latest-master
   on_success:
     attempts: 10
     put: slack-notification
@@ -130,6 +92,107 @@
       text: ':red-circle: Failed to build and push bastion - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>'
       icon_emoji: ':concourse:'
       username: pay-concourse
+- name: bastion-e2e-test-and-retag-image-as-release
+  plan:
+  - in_parallel:
+    - get: bastion-candidate
+      params:
+        format: oci
+      trigger: true
+    - get: pay-ci
+    - get: pay-cli-src
+  - in_parallel:
+      steps:
+      - task: generate-docker-creds-config
+        file: pay-ci/ci/tasks/generate-docker-config-file.yml
+        params:
+          USERNAME: ((docker-username))
+          PASSWORD: ((docker-access-token))
+          EMAIL: ((docker-email))
+      - task: parse-candidate-tag
+        file: pay-ci/ci/tasks/parse-candidate-tag.yml
+        input_mapping:
+          ecr-repo: bastion-candidate
+      - load_var: candidate-image-tag
+        file: bastion-candidate/tag
+  - load_var: release-tag
+    file: parse-candidate-tag/release-tag
+  - task: assume-concourse-role-to-run-e2e-test
+    file: pay-ci/ci/tasks/assume-role.yml
+    params:
+      AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
+      AWS_ROLE_SESSION_NAME: concourser-role
+    output_mapping:
+      assume-role: assume-concourse-role
+  - load_var: concourse_role
+    file: assume-concourse-role/assume-role.json
+  - task: test-bastion
+    file: pay-ci/ci/tasks/run-bastion-e2e.yml
+    params:
+      ECR_REPO: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion
+      IMAGE_TAG: ((.:candidate-image-tag))
+      AWS_DEFAULT_REGION: eu-west-1
+      AWS_ACCESS_KEY_ID: ((.:concourse_role.AWS_ACCESS_KEY_ID))
+      AWS_SECRET_ACCESS_KEY: ((.:concourse_role.AWS_SECRET_ACCESS_KEY))
+      AWS_SESSION_TOKEN: ((.:concourse_role.AWS_SESSION_TOKEN))
+    input_mapping:
+      pay-ci: pay-ci
+      pay-cli: pay-cli-src
+  - task: assume-retag-role
+    file: pay-ci/ci/tasks/assume-role.yml
+    params:
+      AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
+      AWS_ROLE_SESSION_NAME: retag-ecr-image-as-release
+    output_mapping:
+      assume-role: assume-retag-role
+  - load_var: retag-role
+    file: assume-retag-role/assume-role.json
+    format: json
+  - in_parallel:
+      steps:
+      - task: retag-candidate-as-release-in-ecr
+        file: pay-ci/ci/tasks/manifest-retag.yml
+        params:
+          DOCKER_LOGIN_ECR: '1'
+          AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
+          SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
+          NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:release-tag))
+          AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
+          AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
+          AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
+      - task: retag-candidate-as-latest-in-ecr
+        file: pay-ci/ci/tasks/manifest-retag.yml
+        params:
+          DOCKER_LOGIN_ECR: '1'
+          AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
+          SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
+          NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:latest
+          AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
+          AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
+          AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
+      - task: retag-candidate-as-release-in-dockerhub
+        file: pay-ci/ci/tasks/manifest-retag.yml
+        params:
+          SOURCE_MANIFEST: governmentdigitalservice/pay-aws-bastion:((.:candidate-image-tag))
+          NEW_MANIFEST: governmentdigitalservice/pay-aws-bastion:latest-master
+  on_success:
+    attempts: 10
+    put: slack-notification
+    params:
+      channel: '#govuk-pay-activity'
+      silent: true
+      text: ':green-circle: Retagged bastion candidate image ((.:candidate-image-tag)) as release ((.:release-tag)) - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>'
+      icon_emoji: ':concourse:'
+      username: pay-concourse
+  on_failure:
+    attempts: 10
+    put: slack-notification
+    params:
+      channel: '#govuk-pay-starling'
+      silent: true
+      text: ':red-circle: Failed to run bastion E2E test for candidate ((.:candidate-image-tag)) and retag-image as release - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>'
+      icon_emoji: ':concourse:'
+      username: pay-concourse
 - name: deploy-bastion-to-test-12
   plan:
   - in_parallel:
@@ -433,6 +496,26 @@
     aws_ecr_registry_id: ((pay_aws_test_account_id))
     aws_region: eu-west-1
   icon: docker
+- name: bastion-candidate
+  type: registry-image
+  source:
+    repository: govukpay/bastion
+    variant: candidate
+    aws_access_key_id: ((readonly_access_key_id))
+    aws_secret_access_key: ((readonly_secret_access_key))
+    aws_session_token: ((readonly_session_token))
+    aws_role_arn: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
+    aws_ecr_registry_id: ((pay_aws_test_account_id))
+    aws_region: eu-west-1
+  icon: docker
+- name: pay-cli-src
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-cli
+    branch: main
+    username: alphagov-pay-ci-concourse
+    password: ((github-access-token))
+  icon: github
 - name: pipeline-source
   type: git
   source:
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-dev/bastion.pkl`</summary>

```diff
resources:
  resource bastion-candidate has been added:
+ icon: docker
+ name: bastion-candidate
+ source:
+   aws_access_key_id: ((readonly_access_key_id))
+   aws_ecr_registry_id: ((pay_aws_test_account_id))
+   aws_region: eu-west-1
+   aws_role_arn: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
+   aws_secret_access_key: ((readonly_secret_access_key))
+   aws_session_token: ((readonly_session_token))
+   repository: govukpay/bastion
+   variant: candidate
+ type: registry-image
  
  resource pay-cli-src has been added:
+ icon: github
+ name: pay-cli-src
+ source:
+   branch: main
+   password: ((github-access-token))
+   uri: https://github.com/alphagov/pay-cli
+   username: alphagov-pay-ci-concourse
+ type: git
  
jobs:
  job build-and-push-bastion-release has been removed:
- name: build-and-push-bastion-release
- on_failure:
-   attempts: 10
-   params:
-     channel: '#govuk-pay-starling'
-     icon_emoji: ':concourse:'
-     silent: true
-     text: ':red-circle: Failed to build and push bastion - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
-       build #$BUILD_NAME>'
-     username: pay-concourse
-   put: slack-notification
- on_success:
-   attempts: 10
-   params:
-     channel: '#govuk-pay-activity'
-     icon_emoji: ':concourse:'
-     silent: true
-     text: ':green-circle: Built and pushed bastion - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
-       build #$BUILD_NAME>'
-     username: pay-concourse
-   put: slack-notification
- plan:
- - in_parallel:
-     steps:
-     - get: pay-ci
-     - get: bastion-git-release
-       trigger: true
- - in_parallel:
-     steps:
-     - file: pay-ci/ci/tasks/parse-release-tag.yml
-       input_mapping:
-         git-release: bastion-git-release
-       task: parse-release-tag
-     - file: pay-ci/ci/tasks/assume-role.yml
-       params:
-         AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/pay-cd-pay-dev-codebuild-builder-test-12
-         AWS_ROLE_SESSION_NAME: codebuild-assume-role
-       task: assume-role
-     - file: pay-ci/ci/tasks/generate-docker-config-file.yml
-       params:
-         EMAIL: ((docker-email))
-         PASSWORD: ((docker-access-token))
-         USERNAME: ((docker-username))
-       task: generate-docker-creds-config
-     - file: pay-ci/ci/tasks/assume-role.yml
-       output_mapping:
-         assume-role: assume-retag-role
-       params:
-         AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
-         AWS_ROLE_SESSION_NAME: retag-ecr-image-as-release
-       task: assume-retag-role
- - in_parallel:
-     steps:
-     - file: tags/release-number
-       load_var: release-number
-     - file: bastion-git-release/.git/ref
-       load_var: release-name
-     - file: tags/release-sha
-       load_var: release-sha
-     - file: tags/candidate-tag
-       load_var: candidate-image-tag
-     - file: tags/date
-       load_var: date
-     - file: assume-role/assume-role.json
-       format: json
-       load_var: role
-     - file: tags/tags
-       load_var: release-image-tag
-     - file: assume-retag-role/assume-role.json
-       format: json
-       load_var: retag-role
- - file: pay-ci/ci/tasks/prepare-codebuild-multiarch.yml
-   params:
-     AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
-     AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
-     AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
-     BUILD_DATE: ((.:date))
-     ECR_REPO_NAME: govukpay/bastion
-     PROJECT_TO_BUILD: aws-bastion
-     PUSH_TO_DOCKERHUB: "true"
-     RELEASE_NAME: ((.:release-name))
-     RELEASE_NUMBER: ((.:release-number))
-     RELEASE_SHA: ((.:release-sha))
-   task: prepare-codebuild
- - in_parallel:
-     steps:
-     - attempts: 3
-       file: pay-ci/ci/tasks/run-codebuild.yml
-       params:
-         AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
-         AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
-         AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
-         PATH_TO_CONFIG: ../../../../run-codebuild-configuration/aws-bastion-amd64.json
-       task: run-codebuild-aws-bastion-amd64
-     - attempts: 3
-       file: pay-ci/ci/tasks/run-codebuild.yml
-       params:
-         AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
-         AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
-         AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
-         PATH_TO_CONFIG: ../../../../run-codebuild-configuration/aws-bastion-armv8.json
-       task: run-codebuild-aws-bastion-armv8
- - attempts: 3
-   file: pay-ci/ci/tasks/run-codebuild.yml
-   params:
-     AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
-     AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
-     AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
-     PATH_TO_CONFIG: ../../../../run-codebuild-configuration/aws-bastion-manifest.json
-   task: run-codebuild-aws-bastion-manifest
- - in_parallel:
-     steps:
-     - file: pay-ci/ci/tasks/manifest-retag.yml
-       params:
-         AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
-         AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
-         AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
-         AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
-         DOCKER_LOGIN_ECR: "1"
-         NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:release-image-tag))
-         SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
-       task: retag-candidate-as-release-in-ecr
-     - file: pay-ci/ci/tasks/manifest-retag.yml
-       params:
-         AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
-         AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
-         AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
-         AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
-         DOCKER_LOGIN_ECR: "1"
-         NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:latest
-         SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
-       task: retag-candidate-as-latest-in-ecr
-     - file: pay-ci/ci/tasks/manifest-retag.yml
-       params:
-         NEW_MANIFEST: governmentdigitalservice/pay-aws-bastion:latest-master
-         SOURCE_MANIFEST: governmentdigitalservice/pay-aws-bastion:((.:candidate-image-tag))
-       task: retag-candidate-as-release-in-dockerhub
  
  job build-and-push-bastion-candidate has been added:
+ name: build-and-push-bastion-candidate
+ on_failure:
+   attempts: 10
+   params:
+     channel: '#govuk-pay-starling'
+     icon_emoji: ':concourse:'
+     silent: true
+     text: ':red-circle: Failed to build and push bastion - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
+       build #$BUILD_NAME>'
+     username: pay-concourse
+   put: slack-notification
+ on_success:
+   attempts: 10
+   params:
+     channel: '#govuk-pay-activity'
+     icon_emoji: ':concourse:'
+     silent: true
+     text: ':green-circle: Built and pushed bastion - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
+       build #$BUILD_NAME>'
+     username: pay-concourse
+   put: slack-notification
+ plan:
+ - in_parallel:
+     steps:
+     - get: pay-ci
+     - get: bastion-git-release
+       trigger: true
+ - in_parallel:
+     steps:
+     - file: pay-ci/ci/tasks/parse-release-tag.yml
+       input_mapping:
+         git-release: bastion-git-release
+       task: parse-release-tag
+     - file: pay-ci/ci/tasks/assume-role.yml
+       params:
+         AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/pay-cd-pay-dev-codebuild-builder-test-12
+         AWS_ROLE_SESSION_NAME: codebuild-assume-role
+       task: assume-role
+     - file: pay-ci/ci/tasks/generate-docker-config-file.yml
+       params:
+         EMAIL: ((docker-email))
+         PASSWORD: ((docker-access-token))
+         USERNAME: ((docker-username))
+       task: generate-docker-creds-config
+ - in_parallel:
+     steps:
+     - file: tags/release-number
+       load_var: release-number
+     - file: bastion-git-release/.git/ref
+       load_var: release-name
+     - file: tags/release-sha
+       load_var: release-sha
+     - file: tags/candidate-tag
+       load_var: candidate-image-tag
+     - file: tags/date
+       load_var: date
+     - file: assume-role/assume-role.json
+       format: json
+       load_var: role
+ - file: pay-ci/ci/tasks/prepare-codebuild-multiarch.yml
+   params:
+     AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
+     AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
+     AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
+     BUILD_DATE: ((.:date))
+     ECR_REPO_NAME: govukpay/bastion
+     PROJECT_TO_BUILD: aws-bastion
+     PUSH_TO_DOCKERHUB: "true"
+     RELEASE_NAME: ((.:release-name))
+     RELEASE_NUMBER: ((.:release-number))
+     RELEASE_SHA: ((.:release-sha))
+   task: prepare-codebuild
+ - in_parallel:
+     steps:
+     - attempts: 3
+       file: pay-ci/ci/tasks/run-codebuild.yml
+       params:
+         AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
+         AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
+         AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
+         PATH_TO_CONFIG: ../../../../run-codebuild-configuration/aws-bastion-amd64.json
+       task: run-codebuild-aws-bastion-amd64
+     - attempts: 3
+       file: pay-ci/ci/tasks/run-codebuild.yml
+       params:
+         AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
+         AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
+         AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
+         PATH_TO_CONFIG: ../../../../run-codebuild-configuration/aws-bastion-armv8.json
+       task: run-codebuild-aws-bastion-armv8
+ - attempts: 3
+   file: pay-ci/ci/tasks/run-codebuild.yml
+   params:
+     AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
+     AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
+     AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
+     PATH_TO_CONFIG: ../../../../run-codebuild-configuration/aws-bastion-manifest.json
+   task: run-codebuild-aws-bastion-manifest
  
  job bastion-e2e-test-and-retag-image-as-release has been added:
+ name: bastion-e2e-test-and-retag-image-as-release
+ on_failure:
+   attempts: 10
+   params:
+     channel: '#govuk-pay-starling'
+     icon_emoji: ':concourse:'
+     silent: true
+     text: ':red-circle: Failed to run bastion E2E test for candidate ((.:candidate-image-tag))
+       and retag-image as release - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
+       build #$BUILD_NAME>'
+     username: pay-concourse
+   put: slack-notification
+ on_success:
+   attempts: 10
+   params:
+     channel: '#govuk-pay-activity'
+     icon_emoji: ':concourse:'
+     silent: true
+     text: ':green-circle: Retagged bastion candidate image ((.:candidate-image-tag))
+       as release ((.:release-tag)) - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
+       build #$BUILD_NAME>'
+     username: pay-concourse
+   put: slack-notification
+ plan:
+ - in_parallel:
+     steps:
+     - get: bastion-candidate
+       params:
+         format: oci
+       trigger: true
+     - get: pay-ci
+     - get: pay-cli-src
+ - in_parallel:
+     steps:
+     - file: pay-ci/ci/tasks/generate-docker-config-file.yml
+       params:
+         EMAIL: ((docker-email))
+         PASSWORD: ((docker-access-token))
+         USERNAME: ((docker-username))
+       task: generate-docker-creds-config
+     - file: pay-ci/ci/tasks/parse-candidate-tag.yml
+       input_mapping:
+         ecr-repo: bastion-candidate
+       task: parse-candidate-tag
+     - file: bastion-candidate/tag
+       load_var: candidate-image-tag
+ - file: parse-candidate-tag/release-tag
+   load_var: release-tag
+ - file: pay-ci/ci/tasks/assume-role.yml
+   output_mapping:
+     assume-role: assume-concourse-role
+   params:
+     AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
+     AWS_ROLE_SESSION_NAME: concourser-role
+   task: assume-concourse-role-to-run-e2e-test
+ - file: assume-concourse-role/assume-role.json
+   load_var: concourse_role
+ - file: pay-ci/ci/tasks/run-bastion-e2e.yml
+   input_mapping:
+     pay-ci: pay-ci
+     pay-cli: pay-cli-src
+   params:
+     AWS_ACCESS_KEY_ID: ((.:concourse_role.AWS_ACCESS_KEY_ID))
+     AWS_DEFAULT_REGION: eu-west-1
+     AWS_SECRET_ACCESS_KEY: ((.:concourse_role.AWS_SECRET_ACCESS_KEY))
+     AWS_SESSION_TOKEN: ((.:concourse_role.AWS_SESSION_TOKEN))
+     ECR_REPO: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion
+     IMAGE_TAG: ((.:candidate-image-tag))
+   task: test-bastion
+ - file: pay-ci/ci/tasks/assume-role.yml
+   output_mapping:
+     assume-role: assume-retag-role
+   params:
+     AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
+     AWS_ROLE_SESSION_NAME: retag-ecr-image-as-release
+   task: assume-retag-role
+ - file: assume-retag-role/assume-role.json
+   format: json
+   load_var: retag-role
+ - in_parallel:
+     steps:
+     - file: pay-ci/ci/tasks/manifest-retag.yml
+       params:
+         AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
+         AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
+         AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
+         AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
+         DOCKER_LOGIN_ECR: "1"
+         NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:release-tag))
+         SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
+       task: retag-candidate-as-release-in-ecr
+     - file: pay-ci/ci/tasks/manifest-retag.yml
+       params:
+         AWS_ACCESS_KEY_ID: ((.:retag-role.AWS_ACCESS_KEY_ID))
+         AWS_ACCOUNT_ID: ((pay_aws_test_account_id))
+         AWS_SECRET_ACCESS_KEY: ((.:retag-role.AWS_SECRET_ACCESS_KEY))
+         AWS_SESSION_TOKEN: ((.:retag-role.AWS_SESSION_TOKEN))
+         DOCKER_LOGIN_ECR: "1"
+         NEW_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:latest
+         SOURCE_MANIFEST: ((pay_aws_test_account_id)).dkr.ecr.eu-west-1.amazonaws.com/govukpay/bastion:((.:candidate-image-tag))
+       task: retag-candidate-as-latest-in-ecr
+     - file: pay-ci/ci/tasks/manifest-retag.yml
+       params:
+         NEW_MANIFEST: governmentdigitalservice/pay-aws-bastion:latest-master
+         SOURCE_MANIFEST: governmentdigitalservice/pay-aws-bastion:((.:candidate-image-tag))
+       task: retag-candidate-as-release-in-dockerhub
  
pipeline name: bastion

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/cardid-s3.yml
pay-dev/deploy-to-perf.yml
pay-dev/deploy-to-test.yml
pay-dev/e2e-helpers.yml
pay-dev/infra-drift-detector.yml
pay-dev/init-lock-pools.yml
pay-dev/perf-tests.yml
pay-dev/pkl-pipeline-changes.yml
pay-dev/pr-ci.yml
```

**Review by jfharden — APPROVED** [review]
This is all incredible work 🥳

**Pull request merged**
