### PR TITLE
PP-12422 Refactor: move list of apps to separate pkl module

### PR DESCRIPTION
**Pull request by kbottla**
## WHAT
- Moved list of apps to separate pkl module and used in perf and prod pipelines
- Added aliases to avoid lengthy references throughout
- Common tasks in deploy pipelines can be added to `shared_resources_for_deploy_pipelines.pkl`

### CODE REVIEW

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files in Concourse Team pay-deploy**

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/deploy-to-perf.pkl

<details><summary>Diff of YAML generated from pay-dev/deploy-to-perf.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/deploy-to-perf.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/deploy-to-perf.yml
@@ -3376,6 +3376,18 @@
     aws_ecr_registry_id: ((pay_aws_test_account_id))
     aws_region: eu-west-1
   icon: docker
+- name: adot-ecr-registry-perf
+  type: registry-image
+  source:
+    repository: govukpay/adot
+    variant: perf
+    aws_access_key_id: ((readonly_access_key_id))
+    aws_secret_access_key: ((readonly_secret_access_key))
+    aws_session_token: ((readonly_session_token))
+    aws_role_arn: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
+    aws_ecr_registry_id: ((pay_aws_test_account_id))
+    aws_region: eu-west-1
+  icon: docker
 - name: alpine-ecr-registry-perf
   type: registry-image
   source:
```
</details>


Concourse set-pipeline dry-run shows no changes for `pay-dev/deploy-to-perf.pkl`

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/e2e-helpers.yml
pay-dev/pkl-pipeline-changes.yml
```

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files in Concourse Team pay-deploy**

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files in Concourse Team pay-dev**

**Review by jfharden — APPROVED** [review]

**Pull request merged**
