### PR TITLE
PP-12812: Make notifications deploy with loaded tf version and run infra drift detector

### PR DESCRIPTION
**Pull request by jfharden**
I missed a couple from the PR, I just forgot to add the files when committing :(

### CODE REVIEW

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/deploy-to-perf.pkl

<details><summary>Diff of YAML generated from pay-dev/deploy-to-perf.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/deploy-to-perf.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/deploy-to-perf.yml
@@ -1255,7 +1255,7 @@
         type: registry-image
         source:
           repository: hashicorp/terraform
-          tag: 1.3.7
+          tag: ((.:terraform-version))
       inputs:
       - name: pay-infra
       - name: pay-ci
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-dev/deploy-to-perf.pkl`</summary>

```diff
jobs:
  job deploy-notifications-to-perf has changed:
  name: deploy-notifications-to-perf
  on_failure:
    in_parallel:
      steps:
      - attempts: 10
        params:
          channel: '#govuk-pay-announce'
          icon_emoji: ':fargate:'
          silent: true
          text: ':red-circle: Deployment of ((.:app_name)) to perf failed - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
            build #$BUILD_NAME>'
          username: pay-concourse
        put: slack-notification
      - attempts: 3
        params:
          job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/failure
          labels:
            app: ((.:app_name))
            concourse_job: $BUILD_JOB_NAME
            environment: test-perf-1
            instance: concourse
            outcome: failure
            pipeline: $BUILD_PIPELINE_NAME
          metric: deployment_pipeline_app_release_number
          value: ((.:app_release_number))
        put: send-app-release-number-metric
        resource: prometheus-pushgateway
  on_success:
    in_parallel:
      steps:
      - attempts: 10
        params:
          channel: '#govuk-pay-activity'
          icon_emoji: ':fargate:'
          silent: true
          text: ':green-circle: Deployment of ((.:app_name)) to perf success - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
            build #$BUILD_NAME>'
          username: pay-concourse
        put: slack-notification
      - attempts: 3
        params:
          job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/success
          labels:
            app: ((.:app_name))
            concourse_job: $BUILD_JOB_NAME
            environment: test-perf-1
            instance: concourse
            outcome: success
            pipeline: $BUILD_PIPELINE_NAME
          metric: deployment_pipeline_app_release_number
          value: ((.:app_release_number))
        put: send-app-release-number-metric
        resource: prometheus-pushgateway
  plan:
  - in_parallel:
      steps:
      - get: notifications-ecr-registry-perf
        trigger: true
      - get: pay-infra
      - get: pay-ci
  - in_parallel:
      steps:
      - file: pay-ci/ci/tasks/parse-ecr-release-tag.yml
        input_mapping:
          ecr-image: notifications-ecr-registry-perf
        task: parse-notifications-ecr-release-tag
  - in_parallel:
      steps:
      - file: ecr-release-info/app_name
        load_var: app_name
      - file: ecr-release-info/release-number
        load_var: app_release_number
      - file: notifications-ecr-registry-perf/tag
        load_var: application_image_tag
  - params:
      channel: '#govuk-pay-activity'
      icon_emoji: ':fargate:'
      text: ':rocket: Starting notifications deployment to perf - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
        build #$BUILD_NAME>'
      username: pay-concourse
    put: slack-notification
  - file: pay-ci/ci/tasks/assume-role.yml
    params:
      AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
      AWS_ROLE_SESSION_NAME: terraform-test-assume-role
    task: assume-role
  - file: assume-role/assume-role.json
    format: json
    load_var: role
  - file: pay-ci/ci/tasks/find-terraform-version.yml
    params:
      TERRAFORM_ROOT: pay-infra/provisioning/terraform/deployments/test/test-perf-1/microservices_v2/notifications
    task: find-terraform-version
  - file: terraform-version/.terraform-version
    load_var: terraform-version
  - config:
      image_resource:
        name: ""
        source:
          repository: hashicorp/terraform
-         tag: 1.3.7
+         tag: ((.:terraform-version))
        type: registry-image
      inputs:
      - name: pay-infra
      - name: pay-ci
      platform: linux
      run:
        args:
        - pay-ci/ci/scripts/deploy-notifications.sh
        path: /bin/sh
    params:
      ACCOUNT: test
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      ENVIRONMENT: test-perf-1
    task: deploy-to-perf
  - attempts: 3
    params:
      tags:
      - deploy-to-perf
      - ((.:app_name))
      template: released ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME} release ((.:app_release_number))
        (build ${BUILD_ID})
    put: grafana-annotation
  - file: pay-ci/ci/tasks/wait-for-deploy.yml
    params:
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      ENVIRONMENT: test-perf-1
    task: wait-for-deploy
  serial: true
  
pipeline name: deploy-to-perf

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/deploy-to-test.pkl

<details><summary>Diff of YAML generated from pay-dev/deploy-to-test.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/deploy-to-test.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/deploy-to-test.yml
@@ -5350,7 +5350,7 @@
         type: registry-image
         source:
           repository: hashicorp/terraform
-          tag: 1.3.7
+          tag: ((.:terraform-version))
       inputs:
       - name: pay-infra
       - name: pay-ci
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-dev/deploy-to-test.pkl`</summary>

```diff
jobs:
  job deploy-notifications has changed:
  ensure:
    attempts: 3
    params:
      release: claim-deploy-application-test-lock
    put: release-deploy-application-test-lock
    resource: lock-pool-deploy-application-test
  name: deploy-notifications
  on_failure:
    in_parallel:
      steps:
      - params:
          channel: '#govuk-pay-announce'
          icon_emoji: ':fargate:'
          text: "((.:failure_snippet)) \n - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
            build #$BUILD_NAME>"
          username: pay-concourse
        put: slack-notification
      - attempts: 3
        params:
          job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/failure
          labels:
            app: ((.:app_name))
            concourse_job: $BUILD_JOB_NAME
            environment: test-12
            instance: concourse
            outcome: failure
            pipeline: $BUILD_PIPELINE_NAME
          metric: deployment_pipeline_app_release_number
          value: ((.:app_release_number))
        put: send-app-release-number-metric
        resource: prometheus-pushgateway
  on_success:
    in_parallel:
      steps:
      - params:
          channel: '#govuk-pay-activity'
          icon_emoji: ':fargate:'
          text: "((.:success_snippet)) \n - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
            build #$BUILD_NAME>"
          username: pay-concourse
        put: slack-notification
      - attempts: 3
        params:
          job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/success
          labels:
            app: ((.:app_name))
            concourse_job: $BUILD_JOB_NAME
            environment: test-12
            instance: concourse
            outcome: success
            pipeline: $BUILD_PIPELINE_NAME
          metric: deployment_pipeline_app_release_number
          value: ((.:app_release_number))
        put: send-app-release-number-metric
        resource: prometheus-pushgateway
  plan:
  - in_parallel:
      steps:
      - get: notifications-ecr-registry-test
        trigger: true
      - get: pay-infra
      - get: pay-ci
  - attempts: 10
    params:
      claim: deploy-application-test-lock
    put: claim-deploy-application-test-lock
    resource: lock-pool-deploy-application-test
    timeout: 10m
  - in_parallel:
      steps:
      - file: notifications-ecr-registry-test/tag
        load_var: application_image_tag
  - file: pay-ci/ci/tasks/create-notification-snippets.yml
    params:
      ACTION_NAME: Deployment
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      ENV: test-12
    task: create-notification-snippets
  - in_parallel:
      steps:
      - file: snippet/app_name
        load_var: app_name
      - file: snippet/app_release_number
        load_var: app_release_number
      - file: snippet/success
        load_var: success_snippet
      - file: snippet/failure
        load_var: failure_snippet
  - file: pay-ci/ci/tasks/assume-role.yml
    params:
      AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/concourse
      AWS_ROLE_SESSION_NAME: terraform-test-assume-role
    task: assume-role
  - file: assume-role/assume-role.json
    format: json
    load_var: role
  - file: pay-ci/ci/tasks/check-release-versions.yml
    params:
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      CLUSTER_NAME: test-12-fargate
    task: check-release-versions
  - file: pay-ci/ci/tasks/find-terraform-version.yml
    params:
      TERRAFORM_ROOT: pay-infra/provisioning/terraform/deployments/test/test-12/microservices_v2/notifications
    task: find-terraform-version
  - file: terraform-version/.terraform-version
    load_var: terraform-version
  - config:
      image_resource:
        name: ""
        source:
          repository: hashicorp/terraform
-         tag: 1.3.7
+         tag: ((.:terraform-version))
        type: registry-image
      inputs:
      - name: pay-infra
      - name: pay-ci
      platform: linux
      run:
        args:
        - pay-ci/ci/scripts/deploy-notifications.sh
        path: /bin/sh
    params:
      ACCOUNT: test
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      ENVIRONMENT: test-12
    task: deploy-to-test
  - file: pay-ci/ci/tasks/wait-for-deploy.yml
    params:
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      ENVIRONMENT: test-12
    task: wait-for-deploy
  serial: true
  
pipeline name: deploy-to-test

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/bastion.yml
pay-dev/cardid-s3.yml
pay-dev/e2e-helpers.yml
pay-dev/infra-drift-detector.yml
pay-dev/init-lock-pools.yml
pay-dev/perf-tests.yml
pay-dev/pkl-pipeline-changes.yml
pay-dev/pr-ci.yml
```

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-deploy/deploy-to-staging.pkl

<details><summary>Diff of YAML generated from pay-deploy/deploy-to-staging.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-deploy/deploy-to-staging.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-deploy/deploy-to-staging.yml
@@ -4085,7 +4085,7 @@
         type: registry-image
         source:
           repository: hashicorp/terraform
-          tag: 1.3.7
+          tag: ((.:terraform-version))
       inputs:
       - name: pay-infra
       - name: pay-ci
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-deploy/deploy-to-staging.pkl`</summary>

```diff
jobs:
  job deploy-notifications-to-staging has changed:
  ensure:
    attempts: 3
    params:
      release: claim-deploy-application-staging-lock
    put: release-deploy-application-staging-lock
    resource: lock-pool-deploy-application-staging
  name: deploy-notifications-to-staging
  on_failure:
    in_parallel:
      steps:
      - params:
          channel: '#govuk-pay-announce'
          icon_emoji: ':fargate:'
          text: "((.:failure_snippet)) \n - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
            build #$BUILD_NAME>"
          username: pay-concourse
        put: slack-notification
      - attempts: 3
        params:
          job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/failure
          labels:
            app: ((.:app_name))
            concourse_job: $BUILD_JOB_NAME
            environment: staging-2
            instance: concourse
            outcome: failure
            pipeline: $BUILD_PIPELINE_NAME
          metric: deployment_pipeline_app_release_number
          value: ((.:app_release_number))
        put: send-app-release-number-metric
        resource: prometheus-pushgateway
  on_success:
    in_parallel:
      steps:
      - params:
          channel: '#govuk-pay-announce'
          icon_emoji: ':fargate:'
          text: "((.:success_snippet)) \n - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
            build #$BUILD_NAME>"
          username: pay-concourse
        put: slack-notification
      - attempts: 3
        params:
          job: deployment_pipeline_app_release_number/pipeline/$BUILD_PIPELINE_NAME/concourse_job/$BUILD_JOB_NAME/app/((.:app_name))/outcome/success
          labels:
            app: ((.:app_name))
            concourse_job: $BUILD_JOB_NAME
            environment: staging-2
            instance: concourse
            outcome: success
            pipeline: $BUILD_PIPELINE_NAME
          metric: deployment_pipeline_app_release_number
          value: ((.:app_release_number))
        put: send-app-release-number-metric
        resource: prometheus-pushgateway
  plan:
  - in_parallel:
      steps:
      - get: notifications-ecr-registry-staging
        trigger: true
      - get: pay-infra
      - get: pay-ci
  - attempts: 10
    params:
      claim: deploy-application-staging-lock
    put: claim-deploy-application-staging-lock
    resource: lock-pool-deploy-application-staging
    timeout: 10m
  - in_parallel:
      steps:
      - file: pay-ci/ci/tasks/parse-ecr-release-tag.yml
        input_mapping:
          ecr-image: notifications-ecr-registry-staging
        task: parse-notifications-ecr-release-tag
  - in_parallel:
      steps:
      - file: notifications-ecr-registry-staging/tag
        load_var: application_image_tag
  - file: pay-ci/ci/tasks/create-notification-snippets.yml
    params:
      ACTION_NAME: Deployment
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      ENV: staging-2
    task: create-notification-snippets
  - in_parallel:
      steps:
      - file: snippet/app_name
        load_var: app_name
      - file: snippet/app_release_number
        load_var: app_release_number
      - file: snippet/success
        load_var: success_snippet
      - file: snippet/failure
        load_var: failure_snippet
      - file: snippet/start
        load_var: start_snippet
  - params:
      channel: '#govuk-pay-announce'
      icon_emoji: ':fargate:'
      text: "((.:start_snippet)) \n\n <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
        build #$BUILD_NAME>"
      username: pay-concourse
    put: slack-notification
  - file: pay-ci/ci/tasks/assume-role.yml
    output_mapping:
      assume-role: assume-role
    params:
      AWS_ROLE_ARN: arn:aws:iam::((pay_aws_staging_account_id)):role/concourse
      AWS_ROLE_SESSION_NAME: terraform-staging-assume-role
    task: assume-role
  - file: assume-role/assume-role.json
    format: json
    load_var: role
  - file: pay-ci/ci/tasks/check-release-versions.yml
    params:
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      CLUSTER_NAME: staging-2-fargate
    task: check-release-versions
  - file: pay-ci/ci/tasks/find-terraform-version.yml
    params:
      TERRAFORM_ROOT: pay-infra/provisioning/terraform/deployments/staging/staging-2/microservices_v2/notifications
    task: find-terraform-version
  - file: terraform-version/.terraform-version
    load_var: terraform-version
  - config:
      image_resource:
        name: ""
        source:
          repository: hashicorp/terraform
-         tag: 1.3.7
+         tag: ((.:terraform-version))
        type: registry-image
      inputs:
      - name: pay-infra
      - name: pay-ci
      platform: linux
      run:
        args:
        - pay-ci/ci/scripts/deploy-notifications.sh
        path: /bin/sh
    params:
      ACCOUNT: staging
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_REGION: eu-west-1
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      ENVIRONMENT: staging-2
    task: deploy-to-staging
  - attempts: 3
    params:
      tags:
      - deploy-to-staging
      - ((.:app_name))
      template: released ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME} release ((.:app_release_number))
        (build ${BUILD_ID})
    put: grafana-annotation
  - file: pay-ci/ci/tasks/wait-for-deploy.yml
    params:
      APP_NAME: notifications
      APPLICATION_IMAGE_TAG: ((.:application_image_tag))
      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
      ENVIRONMENT: staging-2
    task: wait-for-deploy
  serial: true
  
pipeline name: deploy-to-staging

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-deploy/concourse-resources.yml
pay-deploy/concourse-runner.yml
pay-deploy/detect-secrets.yml
pay-deploy/infra-drift-detector.yml
pay-deploy/init-lock-pools.yml
pay-deploy/internal-vulnerability-scan.yml
pay-deploy/node-runner.yml
pay-deploy/pact-broker.yml
pay-deploy/pay-cli.yml
pay-deploy/pay-js.yml
pay-deploy/pkl-pipeline-changes.yml
pay-deploy/prometheus-pushgateway.yml
```

**Review by danworth — APPROVED** [review]

**Pull request merged**
