### PR TITLE
PP-13083: Remove CI sns unsubscriber check

### PR DESCRIPTION
**Pull request by jfharden**
The CI account is now closed. Remove the unsubscribed SNS topic check

### CODE REVIEW

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files in Concourse Team pay-deploy**

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/infra-drift-detector.pkl

<details><summary>Diff of YAML generated from pay-dev/infra-drift-detector.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/infra-drift-detector.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/infra-drift-detector.yml
@@ -167,50 +167,6 @@
       text: ':red-circle: SNS subscription check: An SNS topic subscriber is unsubscribed, or has an incorrect subscriber in test - $BUILD_JOB_NAME. - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>'
       icon_emoji: ':concourse:'
       username: pay-concourse
-- name: ci-check-for-zendesk-unsubscribers
-  plan:
-  - in_parallel:
-    - get: every-15-minutes
-      trigger: true
-    - get: pay-ci
-    - get: pay-infra
-  - attempts: 3
-    task: assume-role
-    file: pay-ci/ci/tasks/assume-role.yml
-    params:
-      AWS_ROLE_ARN: arn:aws:iam::((pay_aws_ci_account_id)):role/concourse
-      AWS_ROLE_SESSION_NAME: zendesk-unsubscriber-assume-role
-  - load_var: role
-    file: assume-role/assume-role.json
-    format: json
-  - attempts: 3
-    task: check-sns-subscriptions
-    file: pay-ci/ci/tasks/check-sns-subscriptions.yml
-    params:
-      AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
-      AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
-      AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
-      AWS_REGION: eu-west-1
-      AWS_DEFAULT_REGION: eu-west-1
-      REGIONS: eu-west-1
-  on_success:
-    attempts: 10
-    put: slack-notification
-    params:
-      channel: '#govuk-pay-activity'
-      silent: true
-      text: ':green-circle: SNS subscription check: SNS topic subscribers consistent in ci - $BUILD_JOB_NAME. - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>'
-      icon_emoji: ':concourse:'
-      username: pay-concourse
-  on_failure:
-    attempts: 10
-    put: slack-notification
-    params:
-      channel: '#govuk-pay-starling'
-      silent: true
-      text: ':red-circle: SNS subscription check: An SNS topic subscriber is unsubscribed, or has an incorrect subscriber in ci - $BUILD_JOB_NAME. - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse build #$BUILD_NAME>'
-      icon_emoji: ':concourse:'
-      username: pay-concourse
 - name: dev-check-for-zendesk-unsubscribers
   plan:
   - in_parallel:
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-dev/infra-drift-detector.pkl`</summary>

```diff
jobs:
  job ci-check-for-zendesk-unsubscribers has been removed:
- name: ci-check-for-zendesk-unsubscribers
- on_failure:
-   attempts: 10
-   params:
-     channel: '#govuk-pay-starling'
-     icon_emoji: ':concourse:'
-     silent: true
-     text: ':red-circle: SNS subscription check: An SNS topic subscriber is unsubscribed,
-       or has an incorrect subscriber in ci - $BUILD_JOB_NAME. - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
-       build #$BUILD_NAME>'
-     username: pay-concourse
-   put: slack-notification
- on_success:
-   attempts: 10
-   params:
-     channel: '#govuk-pay-activity'
-     icon_emoji: ':concourse:'
-     silent: true
-     text: ':green-circle: SNS subscription check: SNS topic subscribers consistent
-       in ci - $BUILD_JOB_NAME. - <https://pay-cd.deploy.payments.service.gov.uk/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|Concourse
-       build #$BUILD_NAME>'
-     username: pay-concourse
-   put: slack-notification
- plan:
- - in_parallel:
-     steps:
-     - get: every-15-minutes
-       trigger: true
-     - get: pay-ci
-     - get: pay-infra
- - attempts: 3
-   file: pay-ci/ci/tasks/assume-role.yml
-   params:
-     AWS_ROLE_ARN: arn:aws:iam::((pay_aws_ci_account_id)):role/concourse
-     AWS_ROLE_SESSION_NAME: zendesk-unsubscriber-assume-role
-   task: assume-role
- - file: assume-role/assume-role.json
-   format: json
-   load_var: role
- - attempts: 3
-   file: pay-ci/ci/tasks/check-sns-subscriptions.yml
-   params:
-     AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
-     AWS_DEFAULT_REGION: eu-west-1
-     AWS_REGION: eu-west-1
-     AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
-     AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
-     REGIONS: eu-west-1
-   task: check-sns-subscriptions
  
pipeline name: infra-drift-detector

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/cardid-s3.yml
pay-dev/deploy-to-perf.yml
pay-dev/deploy-to-test.yml
pay-dev/e2e-helpers.yml
pay-dev/init-lock-pools.yml
pay-dev/perf-tests.yml
pay-dev/pkl-pipeline-changes.yml
pay-dev/pr-ci.yml
```

**Review by danworth — APPROVED** [review]
👍

**Pull request merged**
