### PR TITLE
Incident - disable downgrade check for connector

### PR DESCRIPTION
**Pull request by kbottla**
- To revert connector to previous release

### CODE REVIEW

**Review by nlsteers — APPROVED** [review]

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-deploy/concourse-runner.yml
pay-deploy/detect-secrets.yml
pay-deploy/pact-broker.yml
pay-deploy/pay-js.yml
pay-deploy/pkl-pipeline-changes.yml
pay-deploy/prometheus-pushgateway.yml
```

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files in Concourse Team pay-dev**

**Comment by kbottla** [comment]
Applied and deployed previous version of connector

**Comment by kbottla** [comment]
Reverted this

**Pull request closed without merging**
