### PR TITLE
PP-12487 remove submodule update steps, cardid e2e env vars

### PR DESCRIPTION
**Pull request by nlsteers**
### WHAT

- remove submodule tasks
- remove data location overrides for cardid in e2e

### CODE REVIEW

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/pr-ci.pkl

<details><summary>Diff of YAML generated from pay-dev/pr-ci.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pr-ci.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pr-ci.yml
@@ -128,8 +128,6 @@
         status: pending
       get_params:
         skip_download: true
-    - task: update-submodule
-      file: pay-ci/ci/tasks/update-cardid-submodule.yml
   - task: generate-docker-creds-config
     file: pay-ci/ci/tasks/generate-docker-config-file.yml
     params:
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-dev/pr-ci.pkl`</summary>

```diff
jobs:
  job cardid-e2e has changed:
  build_log_retention:
    builds: 500
  max_in_flight: 3
  name: cardid-e2e
  on_failure:
    get_params:
      skip_download: true
    params:
      context: e2e tests
      path: src
      status: failure
    put: cardid-pull-request
  plan:
  - in_parallel:
      steps:
      - get: src
        params:
          integration_tool: checkout
        resource: cardid-pull-request
        trigger: true
        version: every
      - get: pay-ci
  - in_parallel:
      steps:
      - get_params:
          skip_download: true
        params:
          context: e2e tests
          path: src
          status: pending
        put: cardid-pull-request
-     - file: pay-ci/ci/tasks/update-cardid-submodule.yml
-       task: update-submodule
  - file: pay-ci/ci/tasks/generate-docker-config-file.yml
    params:
      EMAIL: ((docker-email))
      PASSWORD: ((docker-access-token))
      USERNAME: ((docker-username))
    task: generate-docker-creds-config
  - file: pay-ci/ci/tasks/build-docker-image.yml
    params:
      app_name: cardid
    privileged: true
    task: build-image
  - in_parallel:
      steps:
      - file: pay-ci/ci/tasks/get-pr-build-docker-image-info.yml
        params:
          app_name: cardid
        task: get-docker-image-info
      - file: pay-ci/ci/tasks/assume-role.yml
        params:
          AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/pay-cd-pay-dev-codebuild-executor-test-12
          AWS_ROLE_SESSION_NAME: e2e-test-assume-role
        task: assume-role
  - in_parallel:
      steps:
      - file: assume-role/assume-role.json
        load_var: role
      - file: image_info/image_filename
        load_var: image_filename
      - file: image_info/tag
        load_var: image_tag
  - in_parallel:
      steps:
      - get_params:
          skip_download: true
        params:
          additional_tags: image_info/tag
          image: local_image/((.:image_filename))
        put: pull-request-builds-ecr
      - file: pay-ci/ci/tasks/prepare-e2e-codebuild.yml
        params:
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          PR_BUILD: "true"
          PROJECT_UNDER_TEST: cardid
          RELEASE_TAG_UNDER_TEST: ((.:image_tag))
        task: prepare-codebuild
  - in_parallel:
      steps:
      - file: pay-ci/ci/tasks/run-codebuild.yml
        params:
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          PATH_TO_CONFIG: ../../../../run-codebuild-configuration/card.json
        task: run-card-e2e-tests
      - file: pay-ci/ci/tasks/run-codebuild.yml
        params:
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          PATH_TO_CONFIG: ../../../../run-codebuild-configuration/zap.json
        task: run-zap-e2e-tests
  - get_params:
      skip_download: true
    params:
      context: e2e tests
      path: src
      status: success
    put: cardid-pull-request
  
pipeline name: pr-ci

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/deploy-to-perf.yml
pay-dev/deploy-to-test.yml
pay-dev/e2e-helpers.yml
pay-dev/infra-drift-detector.yml
pay-dev/init-lock-pools.yml
pay-dev/pkl-pipeline-changes.yml
```

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/pr-ci.pkl

<details><summary>Diff of YAML generated from pay-dev/pr-ci.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pr-ci.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pr-ci.yml
@@ -128,8 +128,6 @@
         status: pending
       get_params:
         skip_download: true
-    - task: update-submodule
-      file: pay-ci/ci/tasks/update-cardid-submodule.yml
   - task: generate-docker-creds-config
     file: pay-ci/ci/tasks/generate-docker-config-file.yml
     params:
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-dev/pr-ci.pkl`</summary>

```diff
jobs:
  job cardid-e2e has changed:
  build_log_retention:
    builds: 500
  max_in_flight: 3
  name: cardid-e2e
  on_failure:
    get_params:
      skip_download: true
    params:
      context: e2e tests
      path: src
      status: failure
    put: cardid-pull-request
  plan:
  - in_parallel:
      steps:
      - get: src
        params:
          integration_tool: checkout
        resource: cardid-pull-request
        trigger: true
        version: every
      - get: pay-ci
  - in_parallel:
      steps:
      - get_params:
          skip_download: true
        params:
          context: e2e tests
          path: src
          status: pending
        put: cardid-pull-request
-     - file: pay-ci/ci/tasks/update-cardid-submodule.yml
-       task: update-submodule
  - file: pay-ci/ci/tasks/generate-docker-config-file.yml
    params:
      EMAIL: ((docker-email))
      PASSWORD: ((docker-access-token))
      USERNAME: ((docker-username))
    task: generate-docker-creds-config
  - file: pay-ci/ci/tasks/build-docker-image.yml
    params:
      app_name: cardid
    privileged: true
    task: build-image
  - in_parallel:
      steps:
      - file: pay-ci/ci/tasks/get-pr-build-docker-image-info.yml
        params:
          app_name: cardid
        task: get-docker-image-info
      - file: pay-ci/ci/tasks/assume-role.yml
        params:
          AWS_ROLE_ARN: arn:aws:iam::((pay_aws_test_account_id)):role/pay-cd-pay-dev-codebuild-executor-test-12
          AWS_ROLE_SESSION_NAME: e2e-test-assume-role
        task: assume-role
  - in_parallel:
      steps:
      - file: assume-role/assume-role.json
        load_var: role
      - file: image_info/image_filename
        load_var: image_filename
      - file: image_info/tag
        load_var: image_tag
  - in_parallel:
      steps:
      - get_params:
          skip_download: true
        params:
          additional_tags: image_info/tag
          image: local_image/((.:image_filename))
        put: pull-request-builds-ecr
      - file: pay-ci/ci/tasks/prepare-e2e-codebuild.yml
        params:
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          PR_BUILD: "true"
          PROJECT_UNDER_TEST: cardid
          RELEASE_TAG_UNDER_TEST: ((.:image_tag))
        task: prepare-codebuild
  - in_parallel:
      steps:
      - file: pay-ci/ci/tasks/run-codebuild.yml
        params:
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          PATH_TO_CONFIG: ../../../../run-codebuild-configuration/card.json
        task: run-card-e2e-tests
      - file: pay-ci/ci/tasks/run-codebuild.yml
        params:
          AWS_ACCESS_KEY_ID: ((.:role.AWS_ACCESS_KEY_ID))
          AWS_SECRET_ACCESS_KEY: ((.:role.AWS_SECRET_ACCESS_KEY))
          AWS_SESSION_TOKEN: ((.:role.AWS_SESSION_TOKEN))
          PATH_TO_CONFIG: ../../../../run-codebuild-configuration/zap.json
        task: run-zap-e2e-tests
  - get_params:
      skip_download: true
    params:
      context: e2e tests
      path: src
      status: success
    put: cardid-pull-request
  
pipeline name: pr-ci

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/deploy-to-perf.yml
pay-dev/deploy-to-test.yml
pay-dev/e2e-helpers.yml
pay-dev/infra-drift-detector.yml
pay-dev/init-lock-pools.yml
pay-dev/pkl-pipeline-changes.yml
```

**Review by jfharden — APPROVED** [review]

**Pull request merged**
