### PR TITLE
PP-12827: Add jobs to report lock status

### PR DESCRIPTION
**Pull request by jfharden**
In preparation for a follow-on PR where a timed job runs with auto-resolves deadlocks, this PR:

* Adds a job for each lock to report the status
* Removes some locks which aren't used anymore since the pr-ci pipeline had most jobs moved out of it

You can see a working report job which showed the unclaimed status of the deploy-applcation-test lock: https://pay-cd.deploy.payments.service.gov.uk/teams/pay-dev/pipelines/init-lock-pools/jobs/report-status-of-deploy-application-test-lock/builds/4
Screenshot 2024-06-27 at 12 53 31

You can also see a working report where it showed the claimed status of the same lock:
Screenshot 2024-06-27 at 12 53 57

The script creates a bunch of outputs which aren't currently used, but I will use as inputs to a later job that decides whether to force unlock or not.

### CODE REVIEW

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-dev/init-lock-pools.pkl

<details><summary>Diff of YAML generated from pay-dev/init-lock-pools.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/init-lock-pools.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/init-lock-pools.yml
@@ -3,36 +3,21 @@
   plan:
   - get: pay-ci
   - task: init-pools
-    file: pay-ci/ci/tasks/init-lock-pools.yml
+    file: pay-ci/ci/tasks/lock-pools/init-lock-pools.yml
     params:
-      POOLS_TO_INIT: deploy-application-test,integration-test,node-test,unit-test,perf-tests,smoke-test-test
+      POOLS_TO_INIT: deploy-application-test,perf-tests,smoke-test-test
   - put: lock-pool-repo
     params:
       repository: lock-pool-repo
       force: 'true'
   - in_parallel:
     - get: deploy-application-test-lock-config
-    - get: integration-test-lock-config
-    - get: node-test-lock-config
-    - get: unit-test-lock-config
     - get: perf-tests-lock-config
     - get: smoke-test-test-lock-config
   - put: add-deploy-application-test-lock
     resource: lock-pool-deploy-application-test
     params:
       add: deploy-application-test-lock-config
-  - put: add-integration-test-lock
-    resource: lock-pool-integration-test
-    params:
-      add: integration-test-lock-config
-  - put: add-node-test-lock
-    resource: lock-pool-node-test
-    params:
-      add: node-test-lock-config
-  - put: add-unit-test-lock
-    resource: lock-pool-unit-test
-    params:
-      add: unit-test-lock-config
   - put: add-perf-tests-lock
     resource: lock-pool-perf-tests
     params:
@@ -50,33 +35,6 @@
     resource: lock-pool-deploy-application-test
     params:
       release: get-already-claimed-deploy-application-test-lock
-- name: force-release-integration-test-lock
-  plan:
-  - get: get-already-claimed-integration-test-lock
-    resource: lock-pool-integration-test
-  - attempts: 3
-    put: release-integration-test-lock
-    resource: lock-pool-integration-test
-    params:
-      release: get-already-claimed-integration-test-lock
-- name: force-release-node-test-lock
-  plan:
-  - get: get-already-claimed-node-test-lock
-    resource: lock-pool-node-test
-  - attempts: 3
-    put: release-node-test-lock
-    resource: lock-pool-node-test
-    params:
-      release: get-already-claimed-node-test-lock
-- name: force-release-unit-test-lock
-  plan:
-  - get: get-already-claimed-unit-test-lock
-    resource: lock-pool-unit-test
-  - attempts: 3
-    put: release-unit-test-lock
-    resource: lock-pool-unit-test
-    params:
-      release: get-already-claimed-unit-test-lock
 - name: force-release-perf-tests-lock
   plan:
   - get: get-already-claimed-perf-tests-lock
@@ -95,6 +53,36 @@
     resource: lock-pool-smoke-test-test
     params:
       release: get-already-claimed-smoke-test-test-lock
+- name: report-status-of-deploy-application-test-lock
+  plan:
+  - in_parallel:
+      steps:
+      - get: lock-pool-repo
+      - get: pay-ci
+  - task: report-status-of-deploy-application-test-lock
+    file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+    params:
+      LOCK_NAME: deploy-application-test
+- name: report-status-of-perf-tests-lock
+  plan:
+  - in_parallel:
+      steps:
+      - get: lock-pool-repo
+      - get: pay-ci
+  - task: report-status-of-perf-tests-lock
+    file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+    params:
+      LOCK_NAME: perf-tests
+- name: report-status-of-smoke-test-test-lock
+  plan:
+  - in_parallel:
+      steps:
+      - get: lock-pool-repo
+      - get: pay-ci
+  - task: report-status-of-smoke-test-test-lock
+    file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+    params:
+      LOCK_NAME: smoke-test-test
 - name: update-pipeline
   plan:
   - get: pipeline-source
@@ -140,48 +128,6 @@
   source:
     create_files:
       name: deploy-application-test-lock
-      metadata: ''
-- name: lock-pool-integration-test
-  type: pay-pool
-  source:
-    branch: pool
-    uri: ((readonly_codecommit_pool_uri))
-    private_key: ((readonly_codecommit_private_key))
-    pool: integration-test
-  icon: pool
-- name: integration-test-lock-config
-  type: mock
-  source:
-    create_files:
-      name: integration-test-lock
-      metadata: ''
-- name: lock-pool-node-test
-  type: pay-pool
-  source:
-    branch: pool
-    uri: ((readonly_codecommit_pool_uri))
-    private_key: ((readonly_codecommit_private_key))
-    pool: node-test
-  icon: pool
-- name: node-test-lock-config
-  type: mock
-  source:
-    create_files:
-      name: node-test-lock
-      metadata: ''
-- name: lock-pool-unit-test
-  type: pay-pool
-  source:
-    branch: pool
-    uri: ((readonly_codecommit_pool_uri))
-    private_key: ((readonly_codecommit_private_key))
-    pool: unit-test
-  icon: pool
-- name: unit-test-lock-config
-  type: mock
-  source:
-    create_files:
-      name: unit-test-lock
       metadata: ''
 - name: lock-pool-perf-tests
   type: pay-pool
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-dev/init-lock-pools.pkl`</summary>

```diff
resources:
  resource integration-test-lock-config has been removed:
- name: integration-test-lock-config
- source:
-   create_files:
-     metadata: ""
-     name: integration-test-lock
- type: mock
  
  resource lock-pool-integration-test has been removed:
- icon: pool
- name: lock-pool-integration-test
- source:
-   branch: pool
-   pool: integration-test
-   private_key: ((readonly_codecommit_private_key))
-   uri: ((readonly_codecommit_pool_uri))
- type: pay-pool
  
  resource lock-pool-node-test has been removed:
- icon: pool
- name: lock-pool-node-test
- source:
-   branch: pool
-   pool: node-test
-   private_key: ((readonly_codecommit_private_key))
-   uri: ((readonly_codecommit_pool_uri))
- type: pay-pool
  
  resource lock-pool-unit-test has been removed:
- icon: pool
- name: lock-pool-unit-test
- source:
-   branch: pool
-   pool: unit-test
-   private_key: ((readonly_codecommit_private_key))
-   uri: ((readonly_codecommit_pool_uri))
- type: pay-pool
  
  resource node-test-lock-config has been removed:
- name: node-test-lock-config
- source:
-   create_files:
-     metadata: ""
-     name: node-test-lock
- type: mock
  
  resource pay-ci has changed:
  icon: github
  name: pay-ci
  source:
-   branch: pp-12827/concourse-surface-lock-owner-info
+   branch: master
    password: ((github-access-token))
    uri: https://github.com/alphagov/pay-ci
    username: alphagov-pay-ci-concourse
  type: git
  
  resource unit-test-lock-config has been removed:
- name: unit-test-lock-config
- source:
-   create_files:
-     metadata: ""
-     name: unit-test-lock
- type: mock
  
jobs:
  job initialise-pools has changed:
  name: initialise-pools
  plan:
  - get: pay-ci
  - file: pay-ci/ci/tasks/lock-pools/init-lock-pools.yml
    params:
-     POOLS_TO_INIT: deploy-application-test,integration-test,node-test,unit-test,perf-tests,smoke-test-test
+     POOLS_TO_INIT: deploy-application-test,perf-tests,smoke-test-test
    task: init-pools
  - params:
      force: "true"
      repository: lock-pool-repo
    put: lock-pool-repo
  - in_parallel:
      steps:
      - get: deploy-application-test-lock-config
-     - get: integration-test-lock-config
-     - get: node-test-lock-config
-     - get: unit-test-lock-config
      - get: perf-tests-lock-config
      - get: smoke-test-test-lock-config
  - params:
      add: deploy-application-test-lock-config
    put: add-deploy-application-test-lock
    resource: lock-pool-deploy-application-test
- - params:
-     add: integration-test-lock-config
-   put: add-integration-test-lock
-   resource: lock-pool-integration-test
- - params:
-     add: node-test-lock-config
-   put: add-node-test-lock
-   resource: lock-pool-node-test
- - params:
-     add: unit-test-lock-config
-   put: add-unit-test-lock
-   resource: lock-pool-unit-test
  - params:
      add: perf-tests-lock-config
    put: add-perf-tests-lock
    resource: lock-pool-perf-tests
  - params:
      add: smoke-test-test-lock-config
    put: add-smoke-test-test-lock
    resource: lock-pool-smoke-test-test
  
  job force-release-integration-test-lock has been removed:
- name: force-release-integration-test-lock
- plan:
- - get: get-already-claimed-integration-test-lock
-   resource: lock-pool-integration-test
- - attempts: 3
-   params:
-     release: get-already-claimed-integration-test-lock
-   put: release-integration-test-lock
-   resource: lock-pool-integration-test
  
  job force-release-node-test-lock has been removed:
- name: force-release-node-test-lock
- plan:
- - get: get-already-claimed-node-test-lock
-   resource: lock-pool-node-test
- - attempts: 3
-   params:
-     release: get-already-claimed-node-test-lock
-   put: release-node-test-lock
-   resource: lock-pool-node-test
  
  job force-release-unit-test-lock has been removed:
- name: force-release-unit-test-lock
- plan:
- - get: get-already-claimed-unit-test-lock
-   resource: lock-pool-unit-test
- - attempts: 3
-   params:
-     release: get-already-claimed-unit-test-lock
-   put: release-unit-test-lock
-   resource: lock-pool-unit-test
  
  job report-status-of-integration-test-lock has been removed:
- name: report-status-of-integration-test-lock
- plan:
- - in_parallel:
-     steps:
-     - get: lock-pool-repo
-     - get: pay-ci
- - file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
-   params:
-     LOCK_NAME: integration-test
-   task: report-status-of-integration-test-lock
  
  job report-status-of-node-test-lock has been removed:
- name: report-status-of-node-test-lock
- plan:
- - in_parallel:
-     steps:
-     - get: lock-pool-repo
-     - get: pay-ci
- - file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
-   params:
-     LOCK_NAME: node-test
-   task: report-status-of-node-test-lock
  
  job report-status-of-unit-test-lock has been removed:
- name: report-status-of-unit-test-lock
- plan:
- - in_parallel:
-     steps:
-     - get: lock-pool-repo
-     - get: pay-ci
- - file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
-   params:
-     LOCK_NAME: unit-test
-   task: report-status-of-unit-test-lock
  
pipeline name: init-lock-pools

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/deploy-to-perf.yml
pay-dev/deploy-to-test.yml
pay-dev/e2e-helpers.yml
pay-dev/infra-drift-detector.yml
pay-dev/perf-tests.yml
pay-dev/pkl-pipeline-changes.yml
pay-dev/pr-ci.yml
```

**Comment by alphagov-pay-ci-concourse** [comment]
# Changes for pay-deploy/init-lock-pools.pkl

<details><summary>Diff of YAML generated from pay-deploy/init-lock-pools.pkl</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-deploy/init-lock-pools.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-deploy/init-lock-pools.yml
@@ -3,7 +3,7 @@
   plan:
   - get: pay-ci
   - task: init-pools
-    file: pay-ci/ci/tasks/init-lock-pools.yml
+    file: pay-ci/ci/tasks/lock-pools/init-lock-pools.yml
     params:
       POOLS_TO_INIT: deploy-application-staging,smoke-test-staging,deploy-application-production,smoke-test-production
   - put: lock-pool-repo
@@ -67,6 +67,46 @@
     resource: lock-pool-smoke-test-production
     params:
       release: get-already-claimed-smoke-test-production-lock
+- name: report-status-of-deploy-application-staging-lock
+  plan:
+  - in_parallel:
+      steps:
+      - get: lock-pool-repo
+      - get: pay-ci
+  - task: report-status-of-deploy-application-staging-lock
+    file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+    params:
+      LOCK_NAME: deploy-application-staging
+- name: report-status-of-smoke-test-staging-lock
+  plan:
+  - in_parallel:
+      steps:
+      - get: lock-pool-repo
+      - get: pay-ci
+  - task: report-status-of-smoke-test-staging-lock
+    file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+    params:
+      LOCK_NAME: smoke-test-staging
+- name: report-status-of-deploy-application-production-lock
+  plan:
+  - in_parallel:
+      steps:
+      - get: lock-pool-repo
+      - get: pay-ci
+  - task: report-status-of-deploy-application-production-lock
+    file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+    params:
+      LOCK_NAME: deploy-application-production
+- name: report-status-of-smoke-test-production-lock
+  plan:
+  - in_parallel:
+      steps:
+      - get: lock-pool-repo
+      - get: pay-ci
+  - task: report-status-of-smoke-test-production-lock
+    file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+    params:
+      LOCK_NAME: smoke-test-production
 - name: update-pipeline
   plan:
   - get: pipeline-source
```
</details>


<details><summary>Concourse set-pipeline dry-run for `pay-deploy/init-lock-pools.pkl`</summary>

```diff
jobs:
  job initialise-pools has changed:
  name: initialise-pools
  plan:
  - get: pay-ci
- - file: pay-ci/ci/tasks/init-lock-pools.yml
+ - file: pay-ci/ci/tasks/lock-pools/init-lock-pools.yml
    params:
      POOLS_TO_INIT: deploy-application-staging,smoke-test-staging,deploy-application-production,smoke-test-production
    task: init-pools
  - params:
      force: "true"
      repository: lock-pool-repo
    put: lock-pool-repo
  - in_parallel:
      steps:
      - get: deploy-application-staging-lock-config
      - get: smoke-test-staging-lock-config
      - get: deploy-application-production-lock-config
      - get: smoke-test-production-lock-config
  - params:
      add: deploy-application-staging-lock-config
    put: add-deploy-application-staging-lock
    resource: lock-pool-deploy-application-staging
  - params:
      add: smoke-test-staging-lock-config
    put: add-smoke-test-staging-lock
    resource: lock-pool-smoke-test-staging
  - params:
      add: deploy-application-production-lock-config
    put: add-deploy-application-production-lock
    resource: lock-pool-deploy-application-production
  - params:
      add: smoke-test-production-lock-config
    put: add-smoke-test-production-lock
    resource: lock-pool-smoke-test-production
  
  job report-status-of-deploy-application-staging-lock has been added:
+ name: report-status-of-deploy-application-staging-lock
+ plan:
+ - in_parallel:
+     steps:
+     - get: lock-pool-repo
+     - get: pay-ci
+ - file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+   params:
+     LOCK_NAME: deploy-application-staging
+   task: report-status-of-deploy-application-staging-lock
  
  job report-status-of-smoke-test-staging-lock has been added:
+ name: report-status-of-smoke-test-staging-lock
+ plan:
+ - in_parallel:
+     steps:
+     - get: lock-pool-repo
+     - get: pay-ci
+ - file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+   params:
+     LOCK_NAME: smoke-test-staging
+   task: report-status-of-smoke-test-staging-lock
  
  job report-status-of-deploy-application-production-lock has been added:
+ name: report-status-of-deploy-application-production-lock
+ plan:
+ - in_parallel:
+     steps:
+     - get: lock-pool-repo
+     - get: pay-ci
+ - file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+   params:
+     LOCK_NAME: deploy-application-production
+   task: report-status-of-deploy-application-production-lock
  
  job report-status-of-smoke-test-production-lock has been added:
+ name: report-status-of-smoke-test-production-lock
+ plan:
+ - in_parallel:
+     steps:
+     - get: lock-pool-repo
+     - get: pay-ci
+ - file: pay-ci/ci/tasks/lock-pools/report-lock-status.yml
+   params:
+     LOCK_NAME: smoke-test-production
+   task: report-status-of-smoke-test-production-lock
  
pipeline name: init-lock-pools

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-deploy/concourse-runner.yml
pay-deploy/deploy-to-production.yml
pay-deploy/deploy-to-staging.yml
pay-deploy/detect-secrets.yml
pay-deploy/infra-drift-detector.yml
pay-deploy/pact-broker.yml
pay-deploy/pay-js.yml
pay-deploy/pkl-pipeline-changes.yml
pay-deploy/pool-resource.yml
pay-deploy/prometheus-pushgateway.yml
```

**Review by rfisher-gds — APPROVED** [review]

**Pull request merged**
