### PR TITLE
PP-9292 Remove *-consumer-pact-test jobs

### PR DESCRIPTION
**Pull request by stephencdaly**
Remove these jobs from the PR pipeline for ledger and adminusers. The
tests that were run by this job are now run as part of the integration
test job.

### CODE REVIEW

**Comment by jfharden** [comment]
We might need to update the Github config to remove these as required tests 🤔

**Comment by stephencdaly** [comment]
> We might need to update the Github config to remove these as required tests 🤔

Github doesn't actually know about these tests as they never report the status. It's `adminusers-as-consumer-pact-test` and `ledger-as-consumer-pact-test` that report the status to GitHub and are required jobs.

**Comment by jfharden** [comment]
Ah cool 👍

**Review by jfharden — APPROVED** [review]
Crackin'

**Pull request merged**
