### PR TITLE
PP-12385: Add github action to comment on the PR with diffs of YML

### PR DESCRIPTION
**Pull request by jfharden**

### CODE REVIEW

**Comment by jfharden** [comment]
Test comment

**Comment by jfharden** [comment]
./pay-deploy/foo.yml` has been deleted. Would require you to run

```
$ fly -t \"pay-deploy\" destroy-pipeline -p \"foo\"
```

**Comment by jfharden** [comment]
<details><summary>Diff of ./pay-deploy/quux.yml</summary>

```diff
--- ci/ci/pkl-pipelines/pay-deploy/quux.yml	2024-03-08 12:17:38
+++ ci-pkl-pull-request/ci/pkl-pipelines/pay-deploy/quux.yml	2024-03-08 12:17:41
@@ -1 +1 @@
-master = "QUUX"
+pr = "QUUX"
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pay-deploy/quux.yml\"</summary>
      
```diff
fly -t "pay-deploy" set-pipeline --dry-run -c "../ci-pkl-pull-request/ci/pkl-pipelines/./pay-deploy/quux.yml" -p "quux"
```

**Comment by jfharden** [comment]
<details><summary>Diff of ./pay-deploy/baz.yml</summary>

```diff
--- ci/ci/pkl-pipelines/pay-deploy/baz.yml	1970-01-01 01:00:00
+++ ci-pkl-pull-request/ci/pkl-pipelines/pay-deploy/baz.yml	2024-03-08 12:17:40
@@ -0,0 +1 @@
+pr = "BAZ"
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pay-deploy/baz.yml\"</summary>
      
```diff
fly -t "pay-deploy" set-pipeline --dry-run -c "../ci-pkl-pull-request/ci/pkl-pipelines/./pay-deploy/baz.yml" -p "baz"
```

**Comment by jfharden** [comment]
-

**Comment by jfharden** [comment]
Test comment with heredoc

**Comment by jfharden** [comment]
`./pay-deploy/foo.yml` has been deleted. Would require you to run

```
$ fly -t \"pay-deploy\" destroy-pipeline -p \"foo\"
```

**Comment by jfharden** [comment]
<details><summary>Diff of ./pay-deploy/quux.yml</summary>

```diff
--- ci/ci/pkl-pipelines/pay-deploy/quux.yml	2024-03-08 12:37:00
+++ ci-pkl-pull-request/ci/pkl-pipelines/pay-deploy/quux.yml	2024-03-08 12:37:03
@@ -1 +1 @@
-master = "QUUX"
+pr = "QUUX"
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pay-deploy/quux.yml\"</summary>
      
```diff
fly -t "pay-deploy" set-pipeline --dry-run -c "../ci-pkl-pull-request/ci/pkl-pipelines/./pay-deploy/quux.yml" -p "quux"
```

**Comment by jfharden** [comment]
<details><summary>Diff of ./pay-deploy/baz.yml</summary>

```diff
--- ci/ci/pkl-pipelines/pay-deploy/baz.yml	1970-01-01 01:00:00
+++ ci-pkl-pull-request/ci/pkl-pipelines/pay-deploy/baz.yml	2024-03-08 12:37:02
@@ -0,0 +1 @@
+pr = "BAZ"
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pay-deploy/baz.yml\"</summary>
      
```diff
fly -t "pay-deploy" set-pipeline --dry-run -c "../ci-pkl-pull-request/ci/pkl-pipelines/./pay-deploy/baz.yml" -p "baz"
```

**Comment by jfharden** [comment]
The following files had no diff in the YAML between the main branch and this PR:

```
pay-dev/bar.yml
```

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files**

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files**

**Comment by alphagov-pay-ci-concourse** [comment]
**No YAML differences detected between PR and master pkl files**

**Comment by alphagov-pay-ci-concourse** [comment]
<details><summary>Diff of ./pkl-pipeline-changes.yml</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
@@ -0,0 +1,63 @@
+jobs:
+- name: comment-pipeline-changes-on-pr
+  plan:
+  - in_parallel:
+    - get: pkl-pipeline-pr
+      trigger: true
+      version: every
+    - get: pay-ci
+  - put: pkl-pipeline-pr
+    params:
+      path: pkl-pipeline-pr
+      status: pending
+      context: test
+    get_params:
+      skip_download: true
+  - on_success:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: success
+        context: test
+      get_params:
+        skip_download: true
+    on_failure:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: failed
+        context: test
+      get_params:
+        skip_download: true
+    task: comment-on-pr-with-yml-and-concourse-diffs
+    file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+    params:
+      GITHUB_TOKEN: ((github-access-token))
+      CONCOURSE_TEAM: pay-dev
+      FLY_PASSWORD: ((readonly_local_user_password))
+resources:
+- name: pay-ci
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-ci
+    branch: master
+  icon: github
+- name: pkl-pipeline-pr
+  type: git
+  source:
+    disable_forks: true
+    repository: alphagov/pay-ci
+    access-token: ((github-access-token))
+    paths:
+    - ci/pkl-pipelines/
+  icon: github
+resource_types:
+- name: pull-request
+  type: registry-image
+  source:
+    respository: teliaoss/github-pr-resource
+    tag: v0.23.0
+groups:
+- name: comment-pipeline-changes-on-pr
+  jobs:
+  - comment-pipeline-changes-on-pr
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pkl-pipeline-changes.yml`</summary>

```diff
resources:
  [0;33mresource pkl-pipeline-pr has changed:[0m
  icon: github
  name: pkl-pipeline-pr
  source:
  [0;31m-[0m [0;31m  access_token: ((github-access-token))[0m
  [0;32m+[0m [0;32m  access-token: ((github-access-token))[0m
    disable_forks: true
    paths:
  [0;31m-[0m [0;31m  - ci/pkl-pipelines/**/*.pkl[0m
  [0;32m+[0m [0;32m  - ci/pkl-pipelines/[0m
    repository: alphagov/pay-ci
  [0;31m-[0m [0;31mtype: pull-request[0m
  [0;32m+[0m [0;32mtype: git[0m
  
resource types:
  [0;33mresource type pull-request has changed:[0m
  name: pull-request
  source:
  [0;31m-[0m [0;31m  repository: teliaoss/github-pr-resource[0m
  [0;32m+[0m [0;32m  respository: teliaoss/github-pr-resource[0m
    tag: v0.23.0
  type: registry-image
  
jobs:
  [0;33mjob comment-pipeline-changes-on-pr has changed:[0m
  name: comment-pipeline-changes-on-pr
  plan:
  - in_parallel:
      steps:
      - get: pkl-pipeline-pr
        trigger: true
        version: every
      - get: pay-ci
  [0;31m-[0m [0;31m- params:[0m
  [0;32m+[0m [0;32m- get_params:[0m
  [0;32m+[0m [0;32m    skip_download: true[0m
  [0;32m+[0m [0;32m  params:[0m
      context: test
      path: pkl-pipeline-pr
      status: pending
    put: pkl-pipeline-pr
  [0;31m-[0m [0;31m- file: pkl-pipeline-pr/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml[0m
  [0;32m+[0m [0;32m- file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml[0m
    on_failure:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: failed
      put: pkl-pipeline-pr
    on_success:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: success
      put: pkl-pipeline-pr
    params:
      CONCOURSE_TEAM: pay-dev
      FLY_PASSWORD: ((readonly_local_user_password))
      GITHUB_TOKEN: ((github-access-token))
    task: comment-on-pr-with-yml-and-concourse-diffs
  
[1mpipeline name: [0mpkl-pipeline-changes

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
<details><summary>Diff of ./pkl-pipeline-changes.yml</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
@@ -0,0 +1,63 @@
+jobs:
+- name: comment-pipeline-changes-on-pr
+  plan:
+  - in_parallel:
+    - get: pkl-pipeline-pr
+      trigger: true
+      version: every
+    - get: pay-ci
+  - put: pkl-pipeline-pr
+    params:
+      path: pkl-pipeline-pr
+      status: pending
+      context: test
+    get_params:
+      skip_download: true
+  - on_success:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: success
+        context: test
+      get_params:
+        skip_download: true
+    on_failure:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: failed
+        context: test
+      get_params:
+        skip_download: true
+    task: comment-on-pr-with-yml-and-concourse-diffs
+    file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+    params:
+      GITHUB_TOKEN: ((github-access-token))
+      CONCOURSE_TEAM: pay-dev
+      FLY_PASSWORD: ((readonly_local_user_password))
+resources:
+- name: pay-ci
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-ci
+    branch: master
+  icon: github
+- name: pkl-pipeline-pr
+  type: git
+  source:
+    disable_forks: true
+    repository: alphagov/pay-ci
+    access-token: ((github-access-token))
+    paths:
+    - ci/pkl-pipelines/
+  icon: github
+resource_types:
+- name: pull-request
+  type: registry-image
+  source:
+    respository: teliaoss/github-pr-resource
+    tag: v0.23.0
+groups:
+- name: comment-pipeline-changes-on-pr
+  jobs:
+  - comment-pipeline-changes-on-pr
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pkl-pipeline-changes.yml`</summary>

```diff
resources:
  resource pkl-pipeline-pr has changed:
  icon: github
  name: pkl-pipeline-pr
  source:
  -   access_token: ((github-access-token))
  +   access-token: ((github-access-token))
    disable_forks: true
    paths:
  -   - ci/pkl-pipelines/**/*.pkl
  +   - ci/pkl-pipelines/
    repository: alphagov/pay-ci
  - type: pull-request
  + type: git
  
resource types:
  resource type pull-request has changed:
  name: pull-request
  source:
  -   repository: teliaoss/github-pr-resource
  +   respository: teliaoss/github-pr-resource
    tag: v0.23.0
  type: registry-image
  
jobs:
  job comment-pipeline-changes-on-pr has changed:
  name: comment-pipeline-changes-on-pr
  plan:
  - in_parallel:
      steps:
      - get: pkl-pipeline-pr
        trigger: true
        version: every
      - get: pay-ci
  - - params:
  + - get_params:
  +     skip_download: true
  +   params:
      context: test
      path: pkl-pipeline-pr
      status: pending
    put: pkl-pipeline-pr
  - - file: pkl-pipeline-pr/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
  + - file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
    on_failure:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: failed
      put: pkl-pipeline-pr
    on_success:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: success
      put: pkl-pipeline-pr
    params:
      CONCOURSE_TEAM: pay-dev
      FLY_PASSWORD: ((readonly_local_user_password))
      GITHUB_TOKEN: ((github-access-token))
    task: comment-on-pr-with-yml-and-concourse-diffs
  
[1mpipeline name: [0mpkl-pipeline-changes

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
<details><summary>Diff of ./pkl-pipeline-changes.yml</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
@@ -0,0 +1,63 @@
+jobs:
+- name: comment-pipeline-changes-on-pr
+  plan:
+  - in_parallel:
+    - get: pkl-pipeline-pr
+      trigger: true
+      version: every
+    - get: pay-ci
+  - put: pkl-pipeline-pr
+    params:
+      path: pkl-pipeline-pr
+      status: pending
+      context: test
+    get_params:
+      skip_download: true
+  - on_success:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: success
+        context: test
+      get_params:
+        skip_download: true
+    on_failure:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: failed
+        context: test
+      get_params:
+        skip_download: true
+    task: comment-on-pr-with-yml-and-concourse-diffs
+    file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+    params:
+      GITHUB_TOKEN: ((github-access-token))
+      CONCOURSE_TEAM: pay-dev
+      FLY_PASSWORD: ((readonly_local_user_password))
+resources:
+- name: pay-ci
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-ci
+    branch: master
+  icon: github
+- name: pkl-pipeline-pr
+  type: git
+  source:
+    disable_forks: true
+    repository: alphagov/pay-ci
+    access-token: ((github-access-token))
+    paths:
+    - ci/pkl-pipelines/
+  icon: github
+resource_types:
+- name: pull-request
+  type: registry-image
+  source:
+    respository: teliaoss/github-pr-resource
+    tag: v0.23.0
+groups:
+- name: comment-pipeline-changes-on-pr
+  jobs:
+  - comment-pipeline-changes-on-pr
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pkl-pipeline-changes.yml`</summary>

```diff
resources:
  resource pkl-pipeline-pr has changed:
  icon: github
  name: pkl-pipeline-pr
  source:
  -   access_token: ((github-access-token))
  +   access-token: ((github-access-token))
    disable_forks: true
    paths:
  -   - ci/pkl-pipelines/**/*.pkl
  +   - ci/pkl-pipelines/
    repository: alphagov/pay-ci
  - type: pull-request
  + type: git
  
resource types:
  resource type pull-request has changed:
  name: pull-request
  source:
  -   repository: teliaoss/github-pr-resource
  +   respository: teliaoss/github-pr-resource
    tag: v0.23.0
  type: registry-image
  
jobs:
  job comment-pipeline-changes-on-pr has changed:
  name: comment-pipeline-changes-on-pr
  plan:
  - in_parallel:
      steps:
      - get: pkl-pipeline-pr
        trigger: true
        version: every
      - get: pay-ci
  - - params:
  + - get_params:
  +     skip_download: true
  +   params:
      context: test
      path: pkl-pipeline-pr
      status: pending
    put: pkl-pipeline-pr
  - - file: pkl-pipeline-pr/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
  + - file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
    on_failure:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: failed
      put: pkl-pipeline-pr
    on_success:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: success
      put: pkl-pipeline-pr
    params:
      CONCOURSE_TEAM: pay-dev
      FLY_PASSWORD: ((readonly_local_user_password))
      GITHUB_TOKEN: ((github-access-token))
    task: comment-on-pr-with-yml-and-concourse-diffs
  
[1mpipeline name: [0mpkl-pipeline-changes

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
<details><summary>Diff of ./pkl-pipeline-changes.yml</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
@@ -0,0 +1,63 @@
+jobs:
+- name: comment-pipeline-changes-on-pr
+  plan:
+  - in_parallel:
+    - get: pkl-pipeline-pr
+      trigger: true
+      version: every
+    - get: pay-ci
+  - put: pkl-pipeline-pr
+    params:
+      path: pkl-pipeline-pr
+      status: pending
+      context: test
+    get_params:
+      skip_download: true
+  - on_success:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: success
+        context: test
+      get_params:
+        skip_download: true
+    on_failure:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: failed
+        context: test
+      get_params:
+        skip_download: true
+    task: comment-on-pr-with-yml-and-concourse-diffs
+    file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+    params:
+      GITHUB_TOKEN: ((github-access-token))
+      CONCOURSE_TEAM: pay-dev
+      FLY_PASSWORD: ((readonly_local_user_password))
+resources:
+- name: pay-ci
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-ci
+    branch: master
+  icon: github
+- name: pkl-pipeline-pr
+  type: git
+  source:
+    disable_forks: true
+    repository: alphagov/pay-ci
+    access-token: ((github-access-token))
+    paths:
+    - ci/pkl-pipelines/
+  icon: github
+resource_types:
+- name: pull-request
+  type: registry-image
+  source:
+    respository: teliaoss/github-pr-resource
+    tag: v0.23.0
+groups:
+- name: comment-pipeline-changes-on-pr
+  jobs:
+  - comment-pipeline-changes-on-pr
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pkl-pipeline-changes.yml`</summary>

```diff
resources:
  resource pkl-pipeline-pr has changed:
  icon: github
  name: pkl-pipeline-pr
  source:
-   access_token: ((github-access-token))
+   access-token: ((github-access-token))
    disable_forks: true
    paths:
-   - ci/pkl-pipelines/**/*.pkl
+   - ci/pkl-pipelines/
    repository: alphagov/pay-ci
- type: pull-request
+ type: git
  
resource types:
  resource type pull-request has changed:
  name: pull-request
  source:
-   repository: teliaoss/github-pr-resource
+   respository: teliaoss/github-pr-resource
    tag: v0.23.0
  type: registry-image
  
jobs:
  job comment-pipeline-changes-on-pr has changed:
  name: comment-pipeline-changes-on-pr
  plan:
  - in_parallel:
      steps:
      - get: pkl-pipeline-pr
        trigger: true
        version: every
      - get: pay-ci
- - params:
+ - get_params:
+     skip_download: true
+   params:
      context: test
      path: pkl-pipeline-pr
      status: pending
    put: pkl-pipeline-pr
- - file: pkl-pipeline-pr/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+ - file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
    on_failure:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: failed
      put: pkl-pipeline-pr
    on_success:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: success
      put: pkl-pipeline-pr
    params:
      CONCOURSE_TEAM: pay-dev
      FLY_PASSWORD: ((readonly_local_user_password))
      GITHUB_TOKEN: ((github-access-token))
    task: comment-on-pr-with-yml-and-concourse-diffs
  
pipeline name: pkl-pipeline-changes

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
<details><summary>Diff of ./pkl-pipeline-changes.yml</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
@@ -0,0 +1,63 @@
+jobs:
+- name: comment-pipeline-changes-on-pr
+  plan:
+  - in_parallel:
+    - get: pkl-pipeline-pr
+      trigger: true
+      version: every
+    - get: pay-ci
+  - put: pkl-pipeline-pr
+    params:
+      path: pkl-pipeline-pr
+      status: pending
+      context: test
+    get_params:
+      skip_download: true
+  - on_success:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: success
+        context: test
+      get_params:
+        skip_download: true
+    on_failure:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: failed
+        context: test
+      get_params:
+        skip_download: true
+    task: comment-on-pr-with-yml-and-concourse-diffs
+    file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+    params:
+      GITHUB_TOKEN: ((github-access-token))
+      CONCOURSE_TEAM: pay-dev
+      FLY_PASSWORD: ((readonly_local_user_password))
+resources:
+- name: pay-ci
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-ci
+    branch: master
+  icon: github
+- name: pkl-pipeline-pr
+  type: git
+  source:
+    disable_forks: true
+    repository: alphagov/pay-ci
+    access-token: ((github-access-token))
+    paths:
+    - ci/pkl-pipelines/
+  icon: github
+resource_types:
+- name: pull-request
+  type: registry-image
+  source:
+    respository: teliaoss/github-pr-resource
+    tag: v0.23.0
+groups:
+- name: comment-pipeline-changes-on-pr
+  jobs:
+  - comment-pipeline-changes-on-pr
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pkl-pipeline-changes.yml`</summary>

```diff
resources:
  resource pkl-pipeline-pr has changed:
  icon: github
  name: pkl-pipeline-pr
  source:
-   access_token: ((github-access-token))
+   access-token: ((github-access-token))
    disable_forks: true
    paths:
-   - ci/pkl-pipelines/**/*.pkl
+   - ci/pkl-pipelines/
    repository: alphagov/pay-ci
- type: pull-request
+ type: git
  
resource types:
  resource type pull-request has changed:
  name: pull-request
  source:
-   repository: teliaoss/github-pr-resource
+   respository: teliaoss/github-pr-resource
    tag: v0.23.0
  type: registry-image
  
jobs:
  job comment-pipeline-changes-on-pr has changed:
  name: comment-pipeline-changes-on-pr
  plan:
  - in_parallel:
      steps:
      - get: pkl-pipeline-pr
        trigger: true
        version: every
      - get: pay-ci
- - params:
+ - get_params:
+     skip_download: true
+   params:
      context: test
      path: pkl-pipeline-pr
      status: pending
    put: pkl-pipeline-pr
- - file: pkl-pipeline-pr/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+ - file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
    on_failure:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: failed
      put: pkl-pipeline-pr
    on_success:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: success
      put: pkl-pipeline-pr
    params:
      CONCOURSE_TEAM: pay-dev
      FLY_PASSWORD: ((readonly_local_user_password))
      GITHUB_TOKEN: ((github-access-token))
    task: comment-on-pr-with-yml-and-concourse-diffs
  
pipeline name: pkl-pipeline-changes

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
<details><summary>Diff of ./pkl-pipeline-changes.yml</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
@@ -0,0 +1,63 @@
+jobs:
+- name: comment-pipeline-changes-on-pr
+  plan:
+  - in_parallel:
+    - get: pkl-pipeline-pr
+      trigger: true
+      version: every
+    - get: pay-ci
+  - put: pkl-pipeline-pr
+    params:
+      path: pkl-pipeline-pr
+      status: pending
+      context: test
+    get_params:
+      skip_download: true
+  - on_success:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: success
+        context: test
+      get_params:
+        skip_download: true
+    on_failure:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: failed
+        context: test
+      get_params:
+        skip_download: true
+    task: comment-on-pr-with-yml-and-concourse-diffs
+    file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+    params:
+      GITHUB_TOKEN: ((github-access-token))
+      CONCOURSE_TEAM: pay-dev
+      FLY_PASSWORD: ((readonly_local_user_password))
+resources:
+- name: pay-ci
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-ci
+    branch: master
+  icon: github
+- name: pkl-pipeline-pr
+  type: git
+  source:
+    disable_forks: true
+    repository: alphagov/pay-ci
+    access-token: ((github-access-token))
+    paths:
+    - ci/pkl-pipelines/
+  icon: github
+resource_types:
+- name: pull-request
+  type: registry-image
+  source:
+    respository: teliaoss/github-pr-resource
+    tag: v0.23.0
+groups:
+- name: comment-pipeline-changes-on-pr
+  jobs:
+  - comment-pipeline-changes-on-pr
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pkl-pipeline-changes.yml`</summary>

```diff
resources:
  resource pkl-pipeline-pr has changed:
  icon: github
  name: pkl-pipeline-pr
  source:
-   access_token: ((github-access-token))
+   access-token: ((github-access-token))
    disable_forks: true
    paths:
-   - ci/pkl-pipelines/**/*.pkl
+   - ci/pkl-pipelines/
    repository: alphagov/pay-ci
- type: pull-request
+ type: git
  
resource types:
  resource type pull-request has changed:
  name: pull-request
  source:
-   repository: teliaoss/github-pr-resource
+   respository: teliaoss/github-pr-resource
    tag: v0.23.0
  type: registry-image
  
jobs:
  job comment-pipeline-changes-on-pr has changed:
  name: comment-pipeline-changes-on-pr
  plan:
  - in_parallel:
      steps:
      - get: pkl-pipeline-pr
        trigger: true
        version: every
      - get: pay-ci
- - params:
+ - get_params:
+     skip_download: true
+   params:
      context: test
      path: pkl-pipeline-pr
      status: pending
    put: pkl-pipeline-pr
- - file: pkl-pipeline-pr/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+ - file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
    on_failure:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: failed
      put: pkl-pipeline-pr
    on_success:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: success
      put: pkl-pipeline-pr
    params:
      CONCOURSE_TEAM: pay-dev
      FLY_PASSWORD: ((readonly_local_user_password))
      GITHUB_TOKEN: ((github-access-token))
    task: comment-on-pr-with-yml-and-concourse-diffs
  
pipeline name: pkl-pipeline-changes

Dry-run mode was set, exiting.
```

**Comment by alphagov-pay-ci-concourse** [comment]
<details><summary>Diff of ./pkl-pipeline-changes.yml</summary>

```diff
--- pay-ci/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
+++ pkl-pipeline-pr/ci/pkl-pipelines/pay-dev/pkl-pipeline-changes.yml
@@ -0,0 +1,63 @@
+jobs:
+- name: comment-pipeline-changes-on-pr
+  plan:
+  - in_parallel:
+    - get: pkl-pipeline-pr
+      trigger: true
+      version: every
+    - get: pay-ci
+  - put: pkl-pipeline-pr
+    params:
+      path: pkl-pipeline-pr
+      status: pending
+      context: test
+    get_params:
+      skip_download: true
+  - on_success:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: success
+        context: test
+      get_params:
+        skip_download: true
+    on_failure:
+      put: pkl-pipeline-pr
+      params:
+        path: pkl-pipeline-pr
+        status: failed
+        context: test
+      get_params:
+        skip_download: true
+    task: comment-on-pr-with-yml-and-concourse-diffs
+    file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+    params:
+      GITHUB_TOKEN: ((github-access-token))
+      CONCOURSE_TEAM: pay-dev
+      FLY_PASSWORD: ((readonly_local_user_password))
+resources:
+- name: pay-ci
+  type: git
+  source:
+    uri: https://github.com/alphagov/pay-ci
+    branch: master
+  icon: github
+- name: pkl-pipeline-pr
+  type: git
+  source:
+    disable_forks: true
+    repository: alphagov/pay-ci
+    access-token: ((github-access-token))
+    paths:
+    - ci/pkl-pipelines/
+  icon: github
+resource_types:
+- name: pull-request
+  type: registry-image
+  source:
+    respository: teliaoss/github-pr-resource
+    tag: v0.23.0
+groups:
+- name: comment-pipeline-changes-on-pr
+  jobs:
+  - comment-pipeline-changes-on-pr
```
</details>
<details><summary>Concourse set-pipeline dry-run for `./pkl-pipeline-changes.yml`</summary>

```diff
resources:
  resource pkl-pipeline-pr has changed:
  icon: github
  name: pkl-pipeline-pr
  source:
-   access_token: ((github-access-token))
+   access-token: ((github-access-token))
    disable_forks: true
    paths:
-   - ci/pkl-pipelines/**/*.pkl
+   - ci/pkl-pipelines/
    repository: alphagov/pay-ci
- type: pull-request
+ type: git
  
resource types:
  resource type pull-request has changed:
  name: pull-request
  source:
-   repository: teliaoss/github-pr-resource
+   respository: teliaoss/github-pr-resource
    tag: v0.23.0
  type: registry-image
  
jobs:
  job comment-pipeline-changes-on-pr has changed:
  name: comment-pipeline-changes-on-pr
  plan:
  - in_parallel:
      steps:
      - get: pkl-pipeline-pr
        trigger: true
        version: every
      - get: pay-ci
- - params:
+ - get_params:
+     skip_download: true
+   params:
      context: test
      path: pkl-pipeline-pr
      status: pending
    put: pkl-pipeline-pr
- - file: pkl-pipeline-pr/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
+ - file: pay-ci/ci/tasks/comment-on-pr-with-pkl-pipeline-diffs.yml
    on_failure:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: failed
      put: pkl-pipeline-pr
    on_success:
      get_params:
        skip_download: true
      params:
        context: test
        path: pkl-pipeline-pr
        status: success
      put: pkl-pipeline-pr
    params:
      CONCOURSE_TEAM: pay-dev
      FLY_PASSWORD: ((readonly_local_user_password))
      GITHUB_TOKEN: ((github-access-token))
    task: comment-on-pr-with-yml-and-concourse-diffs
  
pipeline name: pkl-pipeline-changes

Dry-run mode was set, exiting.
```

**Comment by jfharden** [comment]
This PR ended up with too many painful conflicts, so it's easier to do a new PR completely based on all the previously merged stuff

**Pull request closed without merging**
